name: Create Pull Request Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version like v3.00"
        required: true

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          # input version
          title: ${{ github.event.inputs.version }}
          body: |
            ## Issue

            - [ ] fix #9999

            ## Checklist

            - [ ] 更新游戏版本号

            ## Releas Note

            [b]游戏性更新 v3.0[/b]

            AI添加新英雄 美杜莎。
            优化火女技能施法。
            一些bug修正和平衡性改动。

            [b]Gameplay update v3.0[/b]

            Add medusa to bots pool.
            Improve lina ability usage.
            Fixed some bug and balance.
          branch: develop
          base: main
          reviewers: windybirth
          labels: release

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
